name: wipdemo test

on:
  push:
    branches:
      - 'wip/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  manage-wip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      
      # ✅ Final summary
      - name: Summary
        run: |
          if [ "true" == "false" ]; then
            echo "Consolidate branch created. No PR needed."
          else
            echo "Consolidate branch existed. PR handled."
          fi