name: PR Security Check + Approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ✅ Run Gitleaks scan
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      # 🔐 Trivy FS Scan
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          exit-code: 1
          severity: CRITICAL,HIGH
      

 #       # 🔐 Credential Scanning (FIXED)
 #     - name: Credential Scan (Gitleaks)
 #       uses: gitleaks/gitleaks-action@v2
 #       with:
 #         args: detect --no-git --source=. --redact

 #     - uses: SonarSource/sonarqube-scan-action@v6
 #       env:
 #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 🔥 Quality Gate Check (IMPORTANT)
 #     - name: SonarQube Quality Gate
 #       uses: sonarsource/sonarqube-quality-gate-action@v1
 #       with:
 #         pollingTimeoutSec: 300
 #       env:
 #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      # ✅ Install dependencies
      - name: Install dependencies
        run: npm install

      # ✅ Lint
      - name: Run lint
        run: npm run lint

      # ✅ Run tests
      - name: Run tests
        run: npm test

      # ✅ Build project
      - name: Build app
        run: npm run build

      # ✅ Approve PR ONLY if above step succeeds
      - name: Approve PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          echo "Approving PR #$PR_NUMBER"

          gh pr review $PR_NUMBER --approve
      
      # ✅ Auto Merge PR
      - name: Merge PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          echo "Merging PR #$PR_NUMBER"

          gh pr merge $PR_NUMBER \
            --merge \
#           --delete-branch    
      # ❌ Optional: log failure
      - name: If failed
        if: failure()
        run: |
          echo "❌ Gitleaks failed. PR will NOT be approved."
