name: Build Pipeline

on:
  push:
    branches:
      - consolidate/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Git config
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Extract branch info
      - name: Extract branch info
        id: vars
        run: |
          SOURCE_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Processing: $SOURCE_BRANCH"

          APP=$(echo "$SOURCE_BRANCH" | cut -d'/' -f2 | cut -d'-' -f1)

          TARGET_BRANCH="QA/${APP}"

          echo "source=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
          echo "target=$TARGET_BRANCH" >> $GITHUB_OUTPUT
          echo "app=$APP" >> $GITHUB_OUTPUT

          echo "Target Branch: $TARGET_BRANCH"

      # Check if QA branch exists
      - name: Check if QA branch exists
        id: check
        run: |
          git fetch origin

          if git ls-remote --exit-code --heads origin "${{ steps.vars.outputs.target }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "QA branch exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "QA branch will be created"
          fi

      # Create QA branch if missing
      - name: Create QA branch
        if: steps.check.outputs.exists == 'false'
        run: |
          TARGET="${{ steps.vars.outputs.target }}"

          echo "Creating $TARGET from default branch"
          git checkout origin/${{ github.event.repository.default_branch }} -b "$TARGET"
          git push origin "$TARGET"

      # Fetch QA branch if exists
      - name: Fetch target branch
        if: steps.check.outputs.exists == 'true'
        run: |
          git fetch origin "${{ steps.vars.outputs.target }}"